FROM caddy:<tag>-builder-alpine AS builder
RUN xcaddy build --with github.com/mholt/caddy-l4

FROM caddy:<tag>-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["rm -f /dev/shm/caddy* /dev/shm/xr* && exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"]
